os: linux
sudo: false
language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install flake8
  - pip install paramiko
script:
  - flake8 --verbose
  - PYTHONPATH=. pytest
